### ISSUE TITLE
README verbiage

### ISSUE THREAD

**Issue by mhulse** [charettes/django-admin-enhancer#20]
[README.md](https://github.com/charettes/django-admin-enhancer/blob/aee9e13d57f4233c47fb17e7151008f653e5f47c/README.md):

> The recommended way to install the Debug Toolbar is via pip:

Debug Toolbar, should’t that be Admin Enhancer?

**Comment by mhulse** [comment]
Also, this addon saved my day. Thanks!

Speaking of, if I'm reading the tickets correctly, ticket [#13163](https://code.djangoproject.com/ticket/13163) and [#13165](https://code.djangoproject.com/ticket/13165) have finally been fixed (after 5 years)! :+1: 

Looks like Django 1.8 will have the fix. In the meantime, this plugin will really save some headache. Again, thank you!

**Comment by charettes** [comment]
> Debug Toolbar, should’t that be Admin Enhancer?

Oops that's an embarrassing copy-paste :)

> Also, this addon saved my day. Thanks!

> Speaking of, if I'm reading the tickets correctly, ticket #13163 and #13165 have finally been fixed (after 5 years)! :+1:

> Looks like Django 1.8 will have the fix. In the meantime, this plugin will really save some headache. Again, thank you!

Yes I managed to get things done before the Django 1.8 alpha release django/django@07988744b347302925bc6cc66511e34224db55ab.

I'll keep this ticket open until I find time to reword the README. I'm also planing to port it to Django 1.7.

I'm glad this package saved you some time!

**Comment by mhulse** [comment]
> Oops that's an embarrassing copy-paste :)

Oh! No worries, I do that all the time.

> Yes I managed to get things done before the Django 1.8 alpha release django/django@0798874.

Oh, I did not realize you were the one that patched things! Thank you so much for the addition(s)! :+1: :octocat: 

> I'm also planing to port it to Django 1.7.

Oh, I'm actually using admin-enhancer with Python3.4.x, Django 1.7.2 (django-admin-enhancer 0.1.3.1). I have not noticed any issues so far. Is there anything I should be looking out for?

Also, when Django comes out with this feature built-in, what will be the process for transitioning? I would imagine it'd be as simple as removing admin enhancer from the mixins and installed apps (and removing any collect static assets)?

> I'll keep this ticket open until I find time to reword the README.

Let me know if you need any help.

> I'm glad this package saved you some time!

Yes, thank you so much!

**Comment by charettes** [comment]
I fixed the README and added CI testing against Py3.

It's flaky at best on TravisCI's infrastructure but I've spent a couple of hours trying to get the build to pass. Failures seems to be related to Selenium support there. It's hard to tell what's wrong since the whole tox build passes on my local machine.

Feel free to submit a PR with the required changes in tests to make them past on Travis.

**Comment by mhulse** [comment]
Thank you for all the hard work @charettes! The community owes you some :beers:! :octocat:
