### ISSUE TITLE
wrapper on ManyToMany fields

### ISSUE THREAD

**Issue by nanuxbe** [charettes/django-admin-enhancer#21]
Hi, 

first of all, thank you for this nice widget wrapper :-)

When using the enhancer with a Model with a ManyToManyField, the wrapper is also activated for the ManyToMany field. Although the "add-link" still works correctly, the edit- and delete- links don't work since they are passed an array of keys instead of an integer.

Except for creating a custom dropdown where the edit- and delete- links would be located on each line of the drop-down, I don't really see a good solution for ManyToManyField's so maybe the wrapper should only be enabled for ForeignKey's and not for every RelatedFieldWidgetWrapper

**Comment by charettes** [comment]
Hi @nanuxbe!

Thanks for opening this issue. When I ported this feature to Django (django/django@0798874) I simply disabled it on ManyToManyFields since the UI is was confusing. I'm going to do the same here.

**Comment by nanuxbe** [comment]
Hi,

Yes, I guess it's the best thing to do. I just submitted a pull request which disables it for SelectMultiple's only. But I guess if you already have some working code from Djnago, it's probably better to use that

And thanks for the quick reply
