### ISSUE TITLE
pip install uninstalled my django

### ISSUE THREAD

**Issue by andybak** [charettes/django-admin-enhancer#23]
It's slightly disturbing when that happens. You probably don't want to list Django itself in 'install_requires'

I typed:

```
pip install django-admin-enhancer
```

I saw: 

```
Found existing installation: Django 1.8.2
Uninstalling Django-1.8.2
```

I expected:

```
A warning message? An exception? Maybe even nothing - it might work fine on 1.8...
```

**Comment by andybak** [comment]
Hi, this solves my issue but I just tested and someone on Django < 1.7 running pip install with -U will still have their django upgraded - probably to their surprise and consternation.

**Comment by charettes** [comment]
You shouldn't simply update you Django version without making sure your third party application support this new version. I don't understand why pip doesn't warn you when you try to `pip install "Django==1.8.2" django-admin-enhancer` I can swear it used to tell you it couldn't satisfy all the dependencies.

**Comment by andybak** [comment]
There's two slightly different issues here.
1. Putting both django-admin-enhancer and django<1.7 in requirements.txt
2. Just running pip install django-admin-enhancer from the shell 

There's a 3rd possibility which is that django-admin-enhancer is listed as a requirement of another package in requirements.txt - I didn't test this)

You're correct that (1) seems to work but even (2) is problemmatic as it could cause problems in scenarios where requirements.txt isn't being used. 

Another argument is that of convention. Most Django add-ons don't list Django itself as a requirement. I've only come across one other: https://github.com/markfinger/python-react/issues/30

**Comment by charettes** [comment]
I guess I should remove it from `install_requires` then and maybe raise an `ImproperlyConfigured` exception if `django.VERSION >= (1, 8)`.

**Comment by charettes** [comment]
Like @aaugustin said [here](https://github.com/jazzband/django-debug-toolbar/issues/818) this is really a discussion about how pip should handle `install_requires`. It's the only way for packages to declare dependencies and I really don't think the correct course of action is to force third-party package maintainers to drop them for `pip --upgrade` to behave in a sane way.

**Comment by andybak** [comment]
@charettes. I wanted to try out an app locally just now. It has Django in install_requires. It requires Django < 1.7 actually but the readme didn't mention this.

I typed:

    pip install appname --upgrade-strategy="only-if-needed" 

and it still downgrades my Django install.

**Comment by charettes** [comment]
If you had Django 1.8 installed it makes sense as this application is not compatible with this version.

**Comment by charettes** [comment]
By the way I think `--upgrade-strategy` is only relevant when using the `--upgrade` option.

I understand that you are finding the actual situation of third party application requiring Django a bit frustrating but I think I've invested enough effort and time in this discussion for now. The time I can spend on open source is limited and I prefer investing it in making Django better than fighting over what seems to be an issue with pip and doesn't seem to be an issue for a lot of users.
